# Generated by Django 3.1.4 on 2020-12-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensor_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='storage',
        ),
    ]
