# Generated by Django 3.1.4 on 2021-01-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_remove_sensor_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('temperature', 'Temperature and Humidity'), ('pressure', 'Atmospheric pressure')], default='temperature', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='format',
            field=models.CharField(help_text='Leave empty to use the default format for the sensor (recommended).', max_length=200),
        ),
    ]
