# Generated by Django 4.0.3 on 2022-03-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20210401_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='format',
            field=models.CharField(blank=True, help_text='Deixe em branco para deixar no formato padrão (recomendado).', max_length=200),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('temperatura', 'Temperatura'), ('pressao', 'Pressao'), ('vazao', 'Vazao'), ('bateria', 'Bateria')], default='pressao', max_length=20),
        ),
    ]
